### ISSUE TITLE
siteStream settings in config.yaml resulting in empty _site data object

### ISSUE THREAD

**Issue by jakefromm** [yext/pages#483]
### Describe the bug

In https://github.com/search-laboratory/yext_Homebase, the config.yaml `siteStream` settings are as follows:

```
siteStream:
  id: site-stream
  entityId: site-entity
  fields:
    - id
    - meta
    - name
    - c_searchExperienceAPIKey
  localization:
    locales:
      - en
    primary: false
```

However, the `_site` data object contains no relevant data:
![Screen Shot 2024-01-30 at 1 07 27 PM](https://github.com/yext/pages/assets/88849640/f0e970da-e0f0-450b-9353-ccd15177ff8f)

Based on the code in `config.yaml`, I would expect to see the aforementioned fields in the `_site` object. However please note that the following setup steps were skipped to avoid overwriting existing account configs:
```
3. Run `yext resources apply platform-config/config` to apply the required configuration resources to your account.
4. Run `yext resources apply platform-config/entities` to add the necessary entities to your account. This includes a test location entity which can be deleted before running the apply command if desired.
```

### Reproduction

 https://github.com/search-laboratory/yext_Homebase

### System Info

```shell
Apple M1 Pro, MacOS Monterey v12.6.9
```

### Used Package Manager

npm

### Used Browser

Firefox

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.
